# Generated by Django 5.2.6 on 2025-11-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('TRAINING', 'Training'), ('SEMINAR', 'Seminar'), ('OTHERS', 'Others')], default='MEETING', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
