# Generated by Django 5.2.6 on 2026-02-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_agenda_event_status_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime']},
        ),
    ]
