# Generated by Django 5.2.6 on 2026-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_events_task_responsible_persons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'In Progress'), ('PENDING', 'Pending'), ('HOLDING', 'On Hold'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
